### DISCUSSION TITLE
No matching Manifest Docker Compose

### DISCUSSION THREAD

**Discussion by Iwhite67** [PhlexPlexico/G5V#136] [Q&A]
Hello, i use your docker-compose.yml and when i make docker-compose up, i have this error

i'm on Ubuntu 20.04
`
Pulling g5api (ghcr.io/phlexplexico/g5api:latest)...
latest: Pulling from phlexplexico/g5api
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
`

**Comment by PhlexPlexico** [comment]
Hi!

Very odd you're using Ubuntu, but are you using an arm device like a raspberry Pi? I'm unsure as to why it's looking for an arm64/V8, which it's currently not supported for - as seen here https://github.com/PhlexPlexico/G5V/pkgs/container/g5v

I can try and get it compiled with that architecture, but I believe I was running into some problems previously.

Thanks!

**Comment by Iwhite67** [comment]
yes, i make my test on freebox server
i don't have my prod serv on actualy :p

**Comment by PhlexPlexico** [comment]
That may be why then! That being said, I think the API may have troubles compiling since bcrypt has to be compiled during build... Maybe I'll try adding it, but I can't guarantee it'll work on that arch!

**Comment by Iwhite67** [comment]
i can try on my prod server but i have one question, is a problem to have caddy on same server of nginx ?

i have a server with nginx / mariadb / pterodactyl.

**Comment by PhlexPlexico** [comment]
It shouldn't be an issue! All you have to change in the docker compose is the port and forward requests from NGINX -> Caddy. So in the docker-compose just change the ports under the `caddy` service to something like this - 
```yaml
ports:
  - "9000:80"
```

And on your NGINX you have to find what the IP address and do the forwarding with the reverse proxy and whatnot - so you can probably convert this Caddy setup to Nginx:

```cfg
get5.phlexplexi.co {
   reverse_proxy 172.18.0.5
   request_body {
     max_size 256MB
   }
   route /api/* {
         uri strip_prefix /api
         reverse_proxy http://172.18.0.4:3301
   }
 }
```

Where the 172... addresses are from Docker, using something like the following - 
```bash
docker container inspect G5API | grep -i IPAddress
docker container inspect G5V-Front-End | grep -i IPAddress
```

If mariadb is using the default SQL port, you'll just have to adjust that in your docker-compose as well :) 

TL;DR just setup Nginx as your reverse proxy and adjust ports as necessary!

E: If you wait though, I'll see if I can get that arm build up and running as well.

**Comment by Iwhite67** [comment]
Thanks you, i check this weekend.

**Comment by PhlexPlexico** [comment]
Another thing, in your docker-compose for G5V and G5API, would you mind trying to add `platform: linux/amd64`? For example:

```yaml
g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
      - caddy
    container_name: G5V-Front-End
    restart: always
    platform: linux/amd64
    networks:
      - get5
```

and then try running it? See what happens?

Thanks!

**Comment by Iwhite67** [comment]
I try after eat and I you say


_________________________

Alexis Zaun
Technicien SAV Nord Est

FOM Industrie FRANCE

***@***.******@***.***>
(+33) 06 40 62 82 45
________________________________

**Comment by Iwhite67** [comment]
`
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.g5v: 'platform'
`

**Comment by PhlexPlexico** [comment]
Hmm you may have to bump the `version` at the top to `3` instead of `2`... Very odd, I guess it may not be able to build due to nginx not having that build file either. Very odd, indeed!

Thanks!

**Comment by Iwhite67** [comment]
```
Starting get5db                ... done
Recreating caddy-reverse-proxy ... error
Starting G5API                 ...

ERROR: for caddy-reverse-proxy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/get5/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: mount through procfd: not a directory: unknown: Are you trying to mount a direcStarting G5API                 ... done
```



```
version: '2.1'

networks:
  get5:
    external: true

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-reverse-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - get5
    environment:
      - CADDY_URL=http://match.cs.white-gaming.fr
      - CADDY_API_ENDPOINT=api
      - CADDY_REVERSE_PROXY_PORT=3301
  
  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    networks:
      - get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    volumes: 
      - redisVol:/RedisFiles
    expose:
      - 3301
    environment:
      - PORT=3301
      - HOSTNAME=http://match.cs.white-gaming.fr
      - DBKEY=
      - STEAMAPIKEY=
      - SHAREDSECRET=funzilat
      - CLIENTHOME=http://match.cs.white-gaming.fr
      - APIURL=http://match.cs.white-gaming.fr/api
      - SQLUSER=get5
      - SQLPASSWORD=
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=76561198033164185
      - REDISPASSWORD=
      - UPLOADDEMOS=true
    restart: unless-stopped
    networks:
      - get5

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on: 
      - g5api
      - caddy
    container_name: G5V-Front-End
    restart: always
    networks:
      - get5

volumes:
  redisVol:
    external: false
```

**Reply by Iwhite67** [reply]
> ```
> Starting get5db                ... done
> Recreating caddy-reverse-proxy ... error
> Starting G5API                 ...
> 
> ERROR: for caddy-reverse-proxy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/get5/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: mount through procfd: not a directory: unknown: Are you trying to mount a direcStarting G5API                 ... done
> ```
> 
> ```
> version: '2.1'
> 
> networks:
>   get5:
>     external: true
> 
> services:
>   caddy:
>     image: caddy:2-alpine
>     container_name: caddy-reverse-proxy
>     restart: unless-stopped
>     ports:
>       - "8080:80"
>     volumes: 
>       - ./Caddyfile:/etc/caddy/Caddyfile
>     networks:
>       - get5
>     environment:
>       - CADDY_URL=http://match.cs.white-gaming.fr
>       - CADDY_API_ENDPOINT=api
>       - CADDY_REVERSE_PROXY_PORT=3301
>   
>   get5db:
>     image: yobasystems/alpine-mariadb
>     container_name: get5db
>     restart: always
>     environment:
>       - MYSQL_ROOT_PASSWORD=
>       - MYSQL_DATABASE=get5
>       - MYSQL_USER=get5
>       - MYSQL_PASSWORD=
>     ports:
>       - "3307:3306"
>     networks:
>       - get5
> 
>   g5api:
>     image: ghcr.io/phlexplexico/g5api:latest
>     depends_on:
>       - get5db
>     container_name: G5API
>     volumes: 
>       - redisVol:/RedisFiles
>     expose:
>       - 3301
>     environment:
>       - PORT=3301
>       - HOSTNAME=http://match.cs.white-gaming.fr
>       - DBKEY=
>       - STEAMAPIKEY=
>       - SHAREDSECRET=funzilat
>       - CLIENTHOME=http://match.cs.white-gaming.fr
>       - APIURL=http://match.cs.white-gaming.fr/api
>       - SQLUSER=get5
>       - SQLPASSWORD=
>       - SQLPORT=3306
>       - DATABASE=get5
>       - SQLHOST=get5db
>       - ADMINS=
>       - SUPERADMINS=76561198033164185
>       - REDISPASSWORD=
>       - UPLOADDEMOS=true
>     restart: unless-stopped
>     networks:
>       - get5
> 
>   g5v:
>     image: ghcr.io/phlexplexico/g5v:latest
>     depends_on: 
>       - g5api
>       - caddy
>     container_name: G5V-Front-End
>     restart: always
>     networks:
>       - get5
> 
> volumes:
>   redisVol:
>     external: false
> ```

RIP to me, i have again this error on my serv, i just install debian 11, docker docker-compose and try to docker-compose up

**Reply by PhlexPlexico** [reply]
Do you have the Caddyfile in the same directory as the docker compose file?

**Reply by Iwhite67** [reply]
this is fix, i continue to deploy

**Comment by Iwhite67** [comment]
- ./Caddyfile:/etc/caddy/Caddyfile
to
- ./Caddyfile:/etc/caddy/Caddyfile.conf 

fix

**Comment by Iwhite67** [comment]
so, i have website but problem with API

when i click on sign in

```server{
    # Port listen
    listen 80;

    # DNS Record for catch request
    server_name match.cs.white-gaming.fr;

    # Open block for process forward request
    location /{
        # Server where traffic is transferred
        proxy_pass http://172.18.0.4;
        # Include file proxy_params with general param
        include proxy_params;
    }

        location /api/* {
         proxy_pass http://172.18.0.5:3301;
        include proxy_params;
   }
}
```


![image](https://user-images.githubusercontent.com/9698964/165924499-234dc1c0-aeb5-4fe6-9498-5288ec6a3364.png)

**Comment by PhlexPlexico** [comment]
> * ./Caddyfile:/etc/caddy/Caddyfile
>       to
> 
>     * ./Caddyfile:/etc/caddy/Caddyfile.conf
> 
> 
> fix

This should do nothing. As you can see in the repo, there is a file named `Caddyfile`, please make sure your images are up to date. The Caddyfile is a no extension file and will fail to read on that reverse proxy if you use it like that I think.
https://github.com/PhlexPlexico/G5API/blob/master/Caddyfile



> ```
> Starting get5db                ... done
> Recreating caddy-reverse-proxy ... error
> Starting G5API                 ...
> 
> ERROR: for caddy-reverse-proxy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/get5/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: mount through procfd: not a directory: unknown: Are you trying to mount a direcStarting G5API                 ... done
> ```
> 
> ```
> version: '2.1'
> 
> networks:
>   get5:
>     external: true
> 
> services:
>   caddy:
>     image: caddy:2-alpine
>     container_name: caddy-reverse-proxy
>     restart: unless-stopped
>     ports:
>       - "8080:80"
>     volumes: 
>       - ./Caddyfile:/etc/caddy/Caddyfile
>     networks:
>       - get5
>     environment:
>       - CADDY_URL=http://match.cs.white-gaming.fr
>       - CADDY_API_ENDPOINT=api
>       - CADDY_REVERSE_PROXY_PORT=3301
>   
>   get5db:
>     image: yobasystems/alpine-mariadb
>     container_name: get5db
>     restart: always
>     environment:
>       - MYSQL_ROOT_PASSWORD=
>       - MYSQL_DATABASE=get5
>       - MYSQL_USER=get5
>       - MYSQL_PASSWORD=
>     ports:
>       - "3307:3306"
>     networks:
>       - get5
> 
>   g5api:
>     image: ghcr.io/phlexplexico/g5api:latest
>     depends_on:
>       - get5db
>     container_name: G5API
>     volumes: 
>       - redisVol:/RedisFiles
>     expose:
>       - 3301
>     environment:
>       - PORT=3301
>       - HOSTNAME=http://match.cs.white-gaming.fr
>       - DBKEY=
>       - STEAMAPIKEY=
>       - SHAREDSECRET=funzilat
>       - CLIENTHOME=http://match.cs.white-gaming.fr
>       - APIURL=http://match.cs.white-gaming.fr/api
>       - SQLUSER=get5
>       - SQLPASSWORD=
>       - SQLPORT=3306
>       - DATABASE=get5
>       - SQLHOST=get5db
>       - ADMINS=
>       - SUPERADMINS=76561198033164185
>       - REDISPASSWORD=
>       - UPLOADDEMOS=true
>     restart: unless-stopped
>     networks:
>       - get5
> 
>   g5v:
>     image: ghcr.io/phlexplexico/g5v:latest
>     depends_on: 
>       - g5api
>       - caddy
>     container_name: G5V-Front-End
>     restart: always
>     networks:
>       - get5
> 
> volumes:
>   redisVol:
>     external: false
> ```

As for this, the database is on the wrong port. You changed the port of the database instance so this needs to change as well ` - SQLPORT=3306`.



> so, i have website but problem with API
> 
> when i click on sign in
> 
> ```
>     # Port listen
>     listen 80;
> 
>     # DNS Record for catch request
>     server_name match.cs.white-gaming.fr;
> 
>     # Open block for process forward request
>     location /{
>         # Server where traffic is transferred
>         proxy_pass http://172.18.0.4;
>         # Include file proxy_params with general param
>         include proxy_params;
>     }
> 
>         location /api/* {
>          proxy_pass http://172.18.0.5:3301;
>         include proxy_params;
>    }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/9698964/165924499-234dc1c0-aeb5-4fe6-9498-5288ec6a3364.png)

Per the [wiki](https://github.com/PhlexPlexico/G5V/wiki/Reverse-Proxy-Setup-with-NGINX) - the location for the API block should be as follows:

```conf
location /api/ {
                proxy_pass http://172.18.0.5:3301;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
```

I think the same should be done for the front-end as well.
```conf
location / {
                 proxy_pass http://172.18.0.4;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
```

Since you're not using the reverse proxy, you can remove that caddy image entirely and it shouldn't cause any issues.

**Comment by Iwhite67** [comment]
> > * ./Caddyfile:/etc/caddy/Caddyfile
> >   to
> >   
> >   * ./Caddyfile:/etc/caddy/Caddyfile.conf
> > 
> > fix
> 
> This should do nothing. As you can see in the repo, there is a file named `Caddyfile`, please make sure your images are up to date. The Caddyfile is a no extension file and will fail to read on that reverse proxy if you use it like that I think. https://github.com/PhlexPlexico/G5API/blob/master/Caddyfile
> 

strange, i running on last image

> > ```
> > Starting get5db                ... done
> > Recreating caddy-reverse-proxy ... error
> > Starting G5API                 ...
> > 
> > ERROR: for caddy-reverse-proxy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/get5/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: mount through procfd: not a directory: unknown: Are you trying to mount a direcStarting G5API                 ... done

> 
> As for this, the database is on the wrong port. You changed the port of the database instance so this needs to change as well ` - SQLPORT=3306`.
> 

i have allready a mariadb who running on 3306, i change the port of get5db to 3307:3306


> 
> Per the [wiki](https://github.com/PhlexPlexico/G5V/wiki/Reverse-Proxy-Setup-with-NGINX) - the location for the API block should be as follows:
> 
> ```
> location /api/ {
>                 proxy_pass http://172.18.0.5:3301;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>                 proxy_cache_bypass $http_upgrade;
>         }
> ```
> 
> I think the same should be done for the front-end as well.
> 
> ```
> location / {
>                  proxy_pass http://172.18.0.4;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>                 proxy_cache_bypass $http_upgrade;
>         }
> ```
> 
> Since you're not using the reverse proxy, you can remove that caddy image entirely and it shouldn't cause any issues.

if i remove caddy, i lost the access, but if i keep caddy, i have access

**Comment by PhlexPlexico** [comment]
Well, Caddy is effectively doing nothing if you have your NGINX doing all the proxy requests for you. Did you remove the depends in the g5v part of the docker file?

```yaml
  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on: 
      - g5api
      - caddy
```
Remove caddy from there and try building again, it should run without issue. then grab the IP addresses once more from the containers and update them in your nginx conf.
