### ISSUE TITLE
No login button

### ISSUE THREAD

**Issue by Baldurrr** [PhlexPlexico/G5V#185]
Hi all,

I assume that i have setup everything (g5v + g5api) correctly since i can acces the web page.
I used docker-compose and i only replaced caddy by traefik and still works.

Only thing i'm lost about is how do you connect as admin to the G5V web panel ???
I have no kind of  "steam" button or anything else, see below screenshot:

![Image](https://github.com/user-attachments/assets/39213326-a1bf-40fc-86d4-43f8db8a640b)

The image used for G5V is : ghcr.io/phlexplexico/g5v:latest

As well i have enabled local login and filled my steamid for admins, but no luck.

Thanks for your help 🙂

**Comment by PhlexPlexico** [comment]
You'll need to check your logs of the API. Your reverse proxy to the API is not working. While your when front end may have deployed, the API has failed. Check your logs and make sure the API launched correctly.

E.g. if you go to `https://your.get5.instance/api/matches` does this load an empty JSON response? Or what does it do? Because this is usually signs of your reverse proxy not proxying requests from `https://your.get5.instance/api` -> `http://localhost:3301`.

Thanks!

**Comment by Baldurrr** [comment]
The API is well started and ready 

![Image](https://github.com/user-attachments/assets/db97762e-85d9-4b91-ae1b-e792d64ba210)

I tried to access http://panel.test.lan/api/matches and got 404 not found.
So i tried to bypass the reverse proxy by exposing the API on port 3301 and when i try to reach http://panel.test.lan:3301/api/matches i'm getting "404 not found". 

See log below:
```
0|G5API  | ::ffff:192.168.1.178 - - [13/Apr/2025:14:08:02 +0000] "GET /api/matches HTTP/1.1" 404 21 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
```

I really think something is going on with the image at this point

**Comment by PhlexPlexico** [comment]
> http://panel.test.lan:3301/api/matches

You wouldn't be trying to bypass the reverse proxy at this point. If you expose port 3301, then you would be looking at going to `http://panel.test.lan:3301/matches` instead.

I would suggest looking at your Traefik logs as well to make sure your reverse proxy routing is setup properly. I have all of this setup and tested before I deploy any change, and I can guarantee the latest release works as intended.

I'm not sure how reverse proxy setups work on Traefik, but at the end of the day all it needs to do is reroute external traffic (`https://panel.test.lan/api`) from a specific url, to an internal application. The API itself does not have `/api` prepended for any of its calls. The reverse proxy would strip the `/api` and route it locally, as mentioned in my previous comment where `https://panel.test.lan/api/matches` would modify the URL to strip the `/api` and add the new port to `http://panel.test.lan:3301/matches`. This is done to remove the need for exposing any unnecessary ports to the Internet and allow users to modify the endpoint or host the API on a completely separate server if needed.


ETA: for example,  my current docker setup has a caddy reverse proxy running on a different container since I host a few different apps. That exist on the same docker network so I can use their container names to properly redirect 

And inside my host reverse proxy I have the following setup, I've used comments for examples of what each line should be doing:

```Caddyfile

get5.phlexplexi.co {
  reverse_proxy G5V-Front-End # reverse proxy all web calls to the G5V container running NGINX to serve the Vue app
  Request_body {
  max_size 256MB # extra size to allow larger demo uploads 
  }
  redir /api /api/ # append / to it doesn't write `apimatches but api/matches just in case
  route /api/* {
  # any URI starting with /api/ will now go through this block.
  uri strip_prefix /api # strip /api so /api/matches now becomes /matches 
    reverse_proxy http://G5API:3301 # reverse proxy to local app with the URI of /matches
  }
```


Thanks

**Comment by Baldurrr** [comment]
Sorry for the misreading, the strip tips made it worked 😉

In case anyone want to use traefik, i'm putting the full configuration below :

**docker-compose.yml**
```
services:
  traefik:
    image: "docker.io/traefik:v3.3.4"
    container_name: "traefik"
    hostname: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: ./traefik/conf/traefik.yml
        target: /traefik.yml
      - type: bind
        source: ./traefik/conf/dynamic.yml
        target: /dynamic.yml
      - type: bind
        source: ./traefik/conf/acme.json
        target: /acme.json
    environment:
      - TZ=Europe/Paris
    networks:
      - get5

  redis:
    image: redis:6
    command: redis-server --requirepass changemeredis
    container_name: redis
    networks:
      - get5
    restart: unless-stopped

  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: unless-stopped
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=mysuperrootpassword
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=myotherpassword
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    volumes:
      - ./get5db:/var/lib/mysql

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: g5api
    networks:
      - get5
    volumes:
      - ./get5api:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=
      - STEAMAPIKEY=
      - HOSTNAME=http://panel.test.lan
      - SHAREDSECRET=
      - CLIENTHOME=http://panel.test.lan
      - APIURL=http://panel.test.lan/api
      - SQLUSER=get5
      - SQLPASSWORD=myotherpassword
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=
      - REDISURL=redis://:changemeredis@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=true
    restart: unless-stopped

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: g5v
    networks:
      - get5
    restart: unless-stopped

networks:
  get5:
    external: true
```

**traefik.yml**
```
global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  file:
    filename: /dynamic.yml
    watch: true

api:
  dashboard: false

log:
  level: DEBUG

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
```

**dynamic.yml**
```
http:
  routers:
    get5api:
      entrypoints:
        - web
      rule: "Host(`panel.test.lan`) && PathPrefix(`/api`)"
      service: g5api-container
      middlewares:
        - strip-api
      #priority: 10

    get5view:
      entrypoints:
        - web
      rule: "Host(`panel.test.lan`) && !PathPrefix(`/api`)"
      service: g5v-container

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - "/api"

  services:
    g5api-container:
      loadBalancer:
        servers:
          - url: "http://g5api:3301"

    g5v-container:
      loadBalancer:
        servers:
          - url: "http://g5v:80"
```
