### ISSUE TITLE
how i can install with Apache2?

### ISSUE THREAD

**Issue by strasin** [PhlexPlexico/G5V#188]
how i can install with Apache2?

**Comment by PhlexPlexico** [comment]
Hi, 

If you're running Apache or Tomcat you'll need to find the similar config options to do two things: 
- Set your index directory to the projects `dist` directory (this is created when you run `yarn build` I believe).
- Set the correct reverse proxy config options to point all your API calls from `/api/*` to `http://localhost:3301`.

I've never setup with either tomcat or Apache, so consider it unsupported. It will work, like any other reverse proxy solution, I've just never used it myself, so you may need to troubleshoot. 

Thanks!

**Comment by strasin** [comment]
it's just that when you start Docker, it requires you to stop Apache2 and MySGL, and I have the settings for the main site, the Pelican panel there
when I change the Docker settings for myself, CloudFlare gives me error 521 and the sites don't open

**Comment by PhlexPlexico** [comment]
Well you'd need to remove the `reverse-proxy` in the docker image, and take care of the reverse proxying by yourself via apache. You can always host the MySQL database from docker on a different port, and then adjust the docker compose as necessary so you won't need to stop your MySQL instance that's running on the host.

The docker compose file is only for getting an out of the box with no other services running on your host, so you would need ports 80, 443, 3305 and 3306 open and not in use. Otherwise you'll have to make configuration changes.

**Comment by strasin** [comment]
can u help me configure docker file?

**Comment by strasin** [comment]
great, docker compose with apache

```
services:
  redis:
    image: redis:6
    command: redis-server --requirepass xTK8c53zOQepeh8
    container_name: redis
    networks:
      - get5
    restart: always

  get5db:
    image: mysql
    container_name: get5db
    restart: always
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=iTcVj9741
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=iTcVj9741
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    #ports:
    #  - 3306:3306
    volumes:
      - ./get5db/mysql:/var/lib/mysql

  #caddy:
    #image: lucaslorentz/caddy-docker-proxy:ci-alpine
    #container_name: caddy-reverse-proxy
    #restart: unless-stopped
    #networks:
    #  - get5
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #ports:
    #  - 80:80
    #  - 443:443
    #environment:
    #  - CADDY_INGRESS_NETWORKS=get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    volumes:
      - ./public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=3E3MthQL7jvqGcocv8AWAUMba2JanSN6 #CHANGME https://www.random.org/cgi-bin/randbyte?nbytes=16&format=h
      - STEAMAPIKEY=ML1evcIvGzbKFX6J91H7m4jkcU7wvaNN
      - HOSTNAME=https://matches.goplay.az
      - SHAREDSECRET= 1x8jW99Jmtt6VhejIYq9O9iZ11xPXF
      - CLIENTHOME=https://matches.goplay.az
      - APIURL=https://matches.goplay.az/api
      - SQLUSER=get5
      - SQLPASSWORD=iTcVj9741
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=76561198042563127
      - SUPERADMINS=76561198042563127
      - REDISURL=redis://:Z3fZeK9W6jBfMJY@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=false
    restart: always

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    networks:
      - get5
    restart: always

networks:
  get5:
    external: true
```

**matches.goplay.az.conf**
```
<VirtualHost *:80>
    ServerName matches.goplay.az
    Redirect permanent / https://matches.goplay.az/
</VirtualHost>

<VirtualHost *:443>
    ServerName matches.goplay.az

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/matches.goplay.az/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/matches.goplay.az/privkey.pem

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto https

    # Proxy API requests to the G5API container
    ProxyPass "/api/" "http://172.19.0.4:3301/"
    ProxyPassReverse "/api/" "http://172.19.0.4:3301/"

    # Other requests - in G5V (web interface)
    ProxyPass "/" "http://172.19.0.5:80/"
    ProxyPassReverse "/" "http://172.19.0.5:80/"
</VirtualHost>
```
